"""initial PostgreSQL schema

Revision ID: 63bdbcfda74a
Revises: 
Create Date: 2026-09-25 08:43:48.884009
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '63bdbcfda74a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_name', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('bot_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_bot_config'))
    )
    op.create_table('kits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kits')),
    sa.UniqueConstraint('key', name=op.f('uq_kits_key')),
    sa.UniqueConstraint('name', name=op.f('uq_kits_name'))
    )
    op.create_table('migration_import_issues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'resolved', 'ignored')", name=op.f('ck_migration_import_issues_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_import_issues'))
    )
    op.create_index('ix_migration_issues_category', 'migration_import_issues', ['category'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('discord_role_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'done', 'failed', 'dead_letter')", name=op.f('ck_outbox_events_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_pending', 'outbox_events', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'in_progress')"))
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('ign', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'discord'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('migration', 'discord')", name=op.f('ck_players_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index('uq_players_discord_id', 'players', ['discord_id'], unique=True, postgresql_where=sa.text('discord_id IS NOT NULL'))
    op.create_index('uq_players_ign', 'players', [sa.literal_column('lower(ign)')], unique=True)
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.BigInteger(), nullable=True),
    sa.Column('triggered_by_name', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("mode IN ('preview', 'apply', 'automatic', 'rollback')", name=op.f('ck_sync_runs_mode')),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'partial')", name=op.f('ck_sync_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_table('tier_definitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_retired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('retired_of_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('ladder', 'tournament', 'retired', 'virtual')", name=op.f('ck_tier_definitions_kind')),
    sa.ForeignKeyConstraint(['retired_of_id'], ['tier_definitions.id'], name=op.f('fk_tier_definitions_retired_of_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tier_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_tier_definitions_code'))
    )
    op.create_table('cooldowns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('cooldown_type', sa.Text(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'auto'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cooldown_type IN ('waitlist', 'ht3')", name=op.f('ck_cooldowns_type')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_cooldowns_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_cooldowns_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cooldowns'))
    )
    op.create_index('ix_cooldowns_expiry', 'cooldowns', ['expires_at'], unique=False)
    op.create_index('uq_cooldowns_kit', 'cooldowns', ['player_id', 'kit_id', 'cooldown_type'], unique=True, postgresql_where=sa.text('kit_id IS NOT NULL'))
    op.create_index('uq_cooldowns_waitlist', 'cooldowns', ['player_id'], unique=True, postgresql_where=sa.text("cooldown_type = 'waitlist' AND kit_id IS NULL"))
    op.create_table('evaluations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_evaluations_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_evaluations_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index('uq_eval_active', 'evaluations', ['player_id', 'kit_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('kit_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_kit_roles_kit_id_kits')),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_definitions.id'], name=op.f('fk_kit_roles_tier_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kit_roles')),
    sa.UniqueConstraint('discord_role_id', name='uq_kit_roles_role'),
    sa.UniqueConstraint('kit_id', 'tier_id', name='uq_kit_roles_kit_tier')
    )
    op.create_table('queues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('panel_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('panel_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_queues_kit_id_kits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queues'))
    )
    op.create_index('uq_queue_active_kit', 'queues', ['kit_id'], unique=True, postgresql_where=sa.text('closed_at IS NULL'))
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('result_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluator_id', sa.BigInteger(), nullable=True),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('previous_tier_id', sa.BigInteger(), nullable=True),
    sa.Column('new_tier_id', sa.BigInteger(), nullable=True),
    sa.Column('bridge_tier_id', sa.BigInteger(), nullable=True),
    sa.Column('tier_status', sa.Text(), nullable=True),
    sa.Column('score', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('opponent_id', sa.BigInteger(), nullable=True),
    sa.Column('opponent_name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('eval_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promotion_status', sa.Text(), nullable=True),
    sa.Column('announcement_status', sa.Text(), nullable=True),
    sa.Column('announcement_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("announcement_status IS NULL OR announcement_status IN ('pending', 'sent', 'failed')", name=op.f('ck_results_announcement_status')),
    sa.CheckConstraint("kind IN ('ticket', 'queue', 'ht_fight')", name=op.f('ck_results_kind')),
    sa.CheckConstraint("promotion_status IS NULL OR promotion_status IN ('discord_pending', 'discord_failed', 'committed', 'db_failed_outboxed')", name=op.f('ck_results_promotion_status')),
    sa.ForeignKeyConstraint(['bridge_tier_id'], ['tier_definitions.id'], name=op.f('fk_results_bridge_tier_id_tier_definitions')),
    sa.ForeignKeyConstraint(['evaluator_id'], ['players.id'], name=op.f('fk_results_evaluator_id_players')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_results_kit_id_kits')),
    sa.ForeignKeyConstraint(['new_tier_id'], ['tier_definitions.id'], name=op.f('fk_results_new_tier_id_tier_definitions')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_results_player_id_players')),
    sa.ForeignKeyConstraint(['previous_tier_id'], ['tier_definitions.id'], name=op.f('fk_results_previous_tier_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('result_key', name=op.f('uq_results_result_key'))
    )
    op.create_index('ix_results_player_kit_time', 'results', ['player_id', 'kit_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index('ix_results_promo', 'results', ['promotion_status'], unique=False, postgresql_where=sa.text('promotion_status IS NOT NULL'))
    op.create_index('ix_results_ticket', 'results', ['ticket_channel_id'], unique=False)
    op.create_table('sync_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('kit_id', sa.BigInteger(), nullable=True),
    sa.Column('tier_id', sa.BigInteger(), nullable=True),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=True),
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('anomaly_category', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='applied', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('applied', 'skipped', 'failed', 'anomaly')", name=op.f('ck_sync_actions_status')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_sync_actions_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_sync_actions_player_id_players')),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], name=op.f('fk_sync_actions_sync_run_id_sync_runs')),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_definitions.id'], name=op.f('fk_sync_actions_tier_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_actions'))
    )
    op.create_index('ix_sync_actions_anom', 'sync_actions', ['anomaly_category'], unique=False)
    op.create_index('ix_sync_actions_run', 'sync_actions', ['sync_run_id'], unique=False)
    op.create_table('testers',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_testers_player_id_players')),
    sa.PrimaryKeyConstraint('player_id', name=op.f('pk_testers'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=True),
    sa.Column('ign', sa.Text(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('target_tier_id', sa.BigInteger(), nullable=True),
    sa.Column('current_tier_id', sa.BigInteger(), nullable=True),
    sa.Column('eval', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('claimer_id', sa.BigInteger(), nullable=True),
    sa.Column('claimer_name', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('panel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('ticket_type', sa.Text(), server_default=sa.text("'eval'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'closed')", name=op.f('ck_tickets_status')),
    sa.CheckConstraint("ticket_type IN ('eval', 'fight')", name=op.f('ck_tickets_ticket_type')),
    sa.ForeignKeyConstraint(['claimer_id'], ['players.id'], name=op.f('fk_tickets_claimer_id_players')),
    sa.ForeignKeyConstraint(['current_tier_id'], ['tier_definitions.id'], name=op.f('fk_tickets_current_tier_id_tier_definitions')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_tickets_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_tickets_player_id_players')),
    sa.ForeignKeyConstraint(['target_tier_id'], ['tier_definitions.id'], name=op.f('fk_tickets_target_tier_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_tickets_channel_id'))
    )
    op.create_index('ix_tickets_claimer', 'tickets', ['claimer_id'], unique=False)
    op.create_index('uq_tickets_open_player_kit', 'tickets', ['player_id', 'kit_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('player_current_tiers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_role_id', sa.BigInteger(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('result_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('discord_sync', 'promotion', 'manual')", name=op.f('ck_player_current_tiers_source')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_player_current_tiers_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_current_tiers_player_id_players')),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_player_current_tiers_result_id_results')),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], name=op.f('fk_player_current_tiers_sync_run_id_sync_runs')),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_definitions.id'], name=op.f('fk_player_current_tiers_tier_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_current_tiers')),
    sa.UniqueConstraint('player_id', 'kit_id', name='uq_cur_tier_player_kit')
    )
    op.create_index('ix_cur_tier_kit', 'player_current_tiers', ['kit_id', 'tier_id'], unique=False)
    op.create_index('ix_cur_tier_role', 'player_current_tiers', ['discord_role_id'], unique=False)
    op.create_table('queue_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('queue_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('ign', sa.Text(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'waiting'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pulled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('waiting', 'pulled', 'left', 'tested')", name=op.f('ck_queue_entries_status')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_queue_entries_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_queue_entries_player_id_players')),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name=op.f('fk_queue_entries_queue_id_queues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_entries'))
    )
    op.create_index('ix_queue_position', 'queue_entries', ['queue_id', 'position'], unique=False)
    op.create_index('uq_queue_waiting_player', 'queue_entries', ['queue_id', 'player_id'], unique=True, postgresql_where=sa.text("status = 'waiting'"))
    op.create_table('ticket_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_ticket_members_player_id_players')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_members_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_members')),
    sa.UniqueConstraint('ticket_id', 'player_id', 'added_at', name='uq_ticket_member')
    )
    op.create_table('tier_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('kit_id', sa.BigInteger(), nullable=False),
    sa.Column('tier_id', sa.BigInteger(), nullable=False),
    sa.Column('previous_tier_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('result_id', sa.BigInteger(), nullable=True),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_name', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('promotion', 'discord_sync', 'migration', 'manual', 'rollback')", name=op.f('ck_tier_history_source')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_tier_history_kit_id_kits')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_tier_history_player_id_players')),
    sa.ForeignKeyConstraint(['previous_tier_id'], ['tier_definitions.id'], name=op.f('fk_tier_history_previous_tier_id_tier_definitions')),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_tier_history_result_id_results')),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], name=op.f('fk_tier_history_sync_run_id_sync_runs')),
    sa.ForeignKeyConstraint(['tier_id'], ['tier_definitions.id'], name=op.f('fk_tier_history_tier_id_tier_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tier_history'))
    )
    op.create_index('ix_th_kit', 'tier_history', ['kit_id'], unique=False)
    op.create_index('ix_th_player_kit_time', 'tier_history', ['player_id', 'kit_id', sa.literal_column('changed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_th_player_kit_time', table_name='tier_history')
    op.drop_index('ix_th_kit', table_name='tier_history')
    op.drop_table('tier_history')
    op.drop_table('ticket_members')
    op.drop_index('uq_queue_waiting_player', table_name='queue_entries', postgresql_where=sa.text("status = 'waiting'"))
    op.drop_index('ix_queue_position', table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index('ix_cur_tier_role', table_name='player_current_tiers')
    op.drop_index('ix_cur_tier_kit', table_name='player_current_tiers')
    op.drop_table('player_current_tiers')
    op.drop_index('uq_tickets_open_player_kit', table_name='tickets', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_tickets_claimer', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('testers')
    op.drop_index('ix_sync_actions_run', table_name='sync_actions')
    op.drop_index('ix_sync_actions_anom', table_name='sync_actions')
    op.drop_table('sync_actions')
    op.drop_index('ix_results_ticket', table_name='results')
    op.drop_index('ix_results_promo', table_name='results', postgresql_where=sa.text('promotion_status IS NOT NULL'))
    op.drop_index('ix_results_player_kit_time', table_name='results')
    op.drop_table('results')
    op.drop_index('uq_queue_active_kit', table_name='queues', postgresql_where=sa.text('closed_at IS NULL'))
    op.drop_table('queues')
    op.drop_table('kit_roles')
    op.drop_index('uq_eval_active', table_name='evaluations', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('evaluations')
    op.drop_index('uq_cooldowns_waitlist', table_name='cooldowns', postgresql_where=sa.text("cooldown_type = 'waitlist' AND kit_id IS NULL"))
    op.drop_index('uq_cooldowns_kit', table_name='cooldowns', postgresql_where=sa.text('kit_id IS NOT NULL'))
    op.drop_index('ix_cooldowns_expiry', table_name='cooldowns')
    op.drop_table('cooldowns')
    op.drop_table('tier_definitions')
    op.drop_table('sync_runs')
    op.drop_index('uq_players_ign', table_name='players')
    op.drop_index('uq_players_discord_id', table_name='players', postgresql_where=sa.text('discord_id IS NOT NULL'))
    op.drop_table('players')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', postgresql_where=sa.text("status IN ('pending', 'in_progress')"))
    op.drop_table('outbox_events')
    op.drop_index('ix_migration_issues_category', table_name='migration_import_issues')
    op.drop_table('migration_import_issues')
    op.drop_table('kits')
    op.drop_table('bot_config')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###