"""Phase A/B PostgreSQL package: config, async engine, models, repositories,
services."""

from db import models  # noqa: F401  (registers all tables on Base.metadata)
from db.base import Base, utcnow
from db.config import (
    DatabaseConfigError,
    build_async_database_url,
    build_sync_database_url,
    database_required,
    database_url,
)
from db.engine import (
    create_async_engine_from_url,
    dispose_engine,
    make_session_factory,
)
from db.repositories import (  # noqa: F401  (explicit-session persistence)
    AuditRepository,
    BotConfigRepository,
    CooldownRepository,
    EvaluationRepository,
    KitRepository,
    KitRoleRepository,
    MigrationIssueRepository,
    MirrorRepository,
    MirrorServiceRepository,
    OutboxRepository,
    PlayerIdentityError,
    PlayerRepository,
    QueueEntryRepository,
    QueueRepository,
    ResultRepository,
    SyncActionRepository,
    SyncRunRepository,
    TesterRepository,
    TierDefinitionRepository,
    TierHistoryRepository,
    TicketMemberRepository,
    TicketRepository,
)
from db.services import (  # noqa: F401  (orchestrators, transaction boundaries)
    DiscordSyncService,
    MirrorService,
    OutboxConsumer,
    PromotionCommitService,
    PromotionWedgeOutcome,
    classify_member_roles,
    commit_promotion_with_wedge,
    enqueue_promotion_wedge,
    transaction,
    validate_kit_role_configuration,
)

__all__ = [
    "AuditRepository",
    "Base",
    "BotConfigRepository",
    "CooldownRepository",
    "DatabaseConfigError",
    "DiscordSyncService",
    "EvaluationRepository",
    "KitRepository",
    "KitRoleRepository",
    "MigrationIssueRepository",
    "MirrorRepository",
    "MirrorService",
    "MirrorServiceRepository",
    "OutboxConsumer",
    "OutboxRepository",
    "PlayerIdentityError",
    "PlayerRepository",
    "PromotionCommitService",
    "PromotionWedgeOutcome",
    "QueueEntryRepository",
    "QueueRepository",
    "ResultRepository",
    "SyncActionRepository",
    "SyncRunRepository",
    "TesterRepository",
    "TierDefinitionRepository",
    "TierHistoryRepository",
    "TicketMemberRepository",
    "TicketRepository",
    "build_async_database_url",
    "build_sync_database_url",
    "classify_member_roles",
    "commit_promotion_with_wedge",
    "create_async_engine_from_url",
    "database_required",
    "database_url",
    "dispose_engine",
    "enqueue_promotion_wedge",
    "make_session_factory",
    "models",
    "transaction",
    "utcnow",
    "validate_kit_role_configuration",
]